### PR TITLE
[Request] Add faster page action menu

### PR DESCRIPTION
**Pull request by mickmak-busicat**
**Usage**
1. Click-and-hold at any position.
2. An action menu helper will come out according to current mouse location. (This function not available on mobile device)

**Preview**
screen shot 2016-12-06 at 5 21 16 am

### CODE REVIEW

**Comment by chewong** [comment]
Seems like this PR also contains changes in #29 . Should let #29 merge first, then pull the change from master to this branch :)

**Comment by nodegin** [comment]
Nice idea! but maybe we should also support for mobile devices before releasing this feature

**Comment by mickmak-busicat** [comment]
Agree. I think mobile version can be another PR. It will be quite a big difference on mobile device from layout of it to control method for this feature. (Long tap to show a custom menu is not a good method on mobile). Lets think a good way to do similar function on mobile lol.

**Comment by nodegin** [comment]
@mickmak-busicat I think we can remove the current floating icon and implement this PR on both desktop and mobile, for the former use click & hold and touch and hold for the latter. Can you elaborate why long tap isn't a good solution?

**Comment by mickmak-busicat** [comment]
@nodegin It is because default action of long tap on mobile device can be text selection, image download menu etc lol. It is better not adding custom function with long tap event. 
For mobile version, I would suggest implement a floating menu(like the bottom menu in LIHK app) or take the advantage of some uncommon gestures like triple tap, tap with two fingers etc. to display the menu(but the layout have to be modified to be mobile-friendly). Either way would be good to do shortcut action menu in my opinion lol.

**Comment by nodegin** [comment]
@mickmak-busicat I think single-tap then hold is good for both desktop and mobile

**Comment by mickmak-busicat** [comment]
@nodegin Worth a try. Let me change a little bit to make it works first lol

**Comment by mickmak-busicat** [comment]
Added support for mobile. Feel free to take a look lol

**Comment by nodegin** [comment]
Hi, please sync to master and fix the conflicts!

**Comment by mickmak-busicat** [comment]
Done.

**Comment by nodegin** [comment]
Implemented based on your PR, thanks! (still need improvements)

**Pull request closed without merging**
